/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

extern void assembly_function();

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
uint32_t test_function(uint8_t variable_1, uint16_t variable_2, uint32_t variable_3) {
	volatile uint32_t sum = variable_1 + variable_2 + variable_3;

	if (variable_1 < variable_2) {
		sum += 1;
	}
	return sum;
}


uint32_t test_function2(uint8_t variable_1, uint16_t variable_2, uint32_t variable_3) {
	volatile uint32_t sum = variable_1 + variable_2 + variable_3;

	if (variable_1 < variable_2) {
		sum += 1;
	}
	return sum;
}

uint32_t test_function1(uint8_t variable_1, uint16_t variable_2, uint32_t variable_3) {
	volatile uint32_t sum = variable_1 + variable_2 + variable_3;

	if (variable_1 < variable_2) {
		sum += 1;

		test_function2(variable_1, variable_2, variable_3);
	}
	return sum;
}

*/

int main(void)
{
	/*
	uint8_t v1 = 56;
	uint16_t v2 = 3400;
	uint32_t v3 = 120000;
	uint32_t value = test_function(v1, v2, v3);

	value = test_function2(v1, v2, v3);
*/
	assembly_function();


    /* Loop forever */
	for(;;);
}

