/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f303xc.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


// enable the clocks for desired peripherals (GPIOA, C and E)
void enable_clocks() {

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOEEN;
}

// initialise the discovery board I/O (just outputs: inputs are selected by default)
void initialise_board() {

	// get a pointer to the second half word of the MODER register (for outputs pe8-15)
	uint16_t *led_output_registers = ((uint16_t *)&(GPIOE->MODER)) + 1;
	*led_output_registers = 0x5555;
}


int main(void)
{
	enable_clocks();
	initialise_board();


	uint8_t *led_register = ((uint8_t*)&(GPIOE->ODR)) + 1;
	*led_register = 0b10101010;


	// enable the clock for ADC1
	RCC->AHBENR |= RCC_AHBENR_ADC12EN;

	// set to synchronise the ADC with the clock
	ADC12_COMMON->CCR |= ADC12_CCR_CKMODE_0;

	// ADEN must be = 0 for configuration (is the default)
	ADC1->CR &= ~ADC_CR_ADVREGEN; // clear voltage regulator enable
	ADC1->CR |= ADC_CR_ADVREGEN_0; // set ADVREGEN TO 01

	ADC1->CR &= ~ADC_CR_ADCALDIF; // clear bit to enable Single-ended-input

	// calibrate the ADC (self calibration routine)
	ADC1->CR |= ADC_CR_ADCAL;
	while((ADC1->CR & ADC_CR_ADCAL) == ADC_CR_ADCAL); // Waiting for the calibration to finish

	// select the channel
	ADC1->SQR1 = 0; // clear any existing channel requests
	ADC1->SQR1 |= ADC_SQR1_SQ1_1; // set the request for channel 2

	// single shot mode
	ADC1->CFGR &= ~ADC_CFGR_CONT;

	ADC1->CR |= ADC_CR_ADEN; //Enabling ADC

	while (ADC1->ISR == 0); //Wait the ADC to be ready.


    /* Loop forever */
	for(;;) {

		// request the process to start
		ADC1->CR |= ADC_CR_ADSTART;

		// Wait for the end of conversion
		while((ADC1->ISR &= ADC_ISR_EOS) != ADC_ISR_EOS);

		// read the value from ADC1->DR, full range is 12 bits (0xFFF maximum)
		uint8_t scale = ADC1->DR / (0xfff / 8);  // divide the scale into 8 even partitions (for 8 leds)

		if (scale > 7) {
			scale = 7;
		}

		*led_register = pow(2, scale);

	}
}
